# Generated by Django 3.1.4 on 2020-12-17 05:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 17, 5, 38, 45, 847546, tzinfo=utc)),
        ),
    ]
