# Generated by Django 3.1.4 on 2020-12-19 09:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='textPost',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
