# Generated by Django 3.1.4 on 2020-12-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20201219_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagePost',
            field=models.ImageField(blank=True, null=True, upload_to='imagesPost/'),
        ),
    ]
