# Generated by Django 3.1.4 on 2020-12-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='linkvk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
