# Generated by Django 3.1.4 on 2020-12-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
